---
- alias: Open Shutter window open
  trigger:
    platform: state
    entity_id: binary_sensor.bs_ki_window_contact
    to: 'on'
  condition:
    - condition: state
      entity_id: cover.jalousie_kueche_position
      state: 'closed'
  action:
    - service: cover.open_cover
      entity_id: cover.jalousie_kueche_position

- alias: Close cover after airing
  trigger:
    platform: state
    entity_id: binary_sensor.bs_ki_window_contact
    to: 'off'
  condition:
    - condition: sun
      after: sunset
  action:
    - service: cover.close_cover
      entity_id: cover.jalousie_kueche_position
