---
- platform: min_max
  entity_ids:
    - sensor.wohnzimmer_multisensor_temperature_air
    - sensor.se_dr_temp_temperature
    - sensor.se_lr_temp_temperature
  type: median
  name: temperature_livingroom

- platform: min_max
  entity_ids:
    - sensor.se_of_pt_temp_temperature
  type: median
  name: temperature_office

- platform: min_max
  entity_ids:
    - sensor.kuche_sensor_temperature
    - sensor.bs_ki_window_temperature
  type: median
  name: temperature_kitchen

- platform: min_max
  entity_ids:
    - sensor.bs_hw_bm_door_temperature
    - sensor.flur_sensor_temperature
    - sensor.se_hw_temp_temperature
  type: median
  name: temperature_hallway

- platform: min_max
  entity_ids:
    - sensor.se_br_temp_temperature
    - sensor.bs_br_window_temperature
  type: median
  name: temperature_bathroom

- platform: min_max
  entity_ids:
    - sensor.se_mbr_temp_temperature
  type: median
  name: temperature_bedroom

- platform: min_max
  entity_ids:
    - sensor.temperature_wohnzimmer
    - sensor.temperature_arbeitszimmer
    - sensor.temperature_kitchen
    - sensor.temperature_bathroom
    - sensor.temperature_hallway
    - sensor.temperature_bedroom
  type: median
  name: temperature_house