---
homeassistant:
  name: Casa Lani
  latitude: !secret HASS_LATITUDE
  longitude: !secret HASS_LONGITUDE
  elevation: !secret HASS_ELEVATION
  unit_system: metric
  currency: EUR
  time_zone: Europe/Berlin
  country: DE
  # Customization file
  customize: !include_dir_merge_named customizations/
  # Load packages
  legacy_templates: true
  packages: !include_dir_named packages
  external_url: "https://home.casalani.de"
  internal_url: "https://home.casalani.de"

############################################################################
# Configuration
############################################################################

automation: !include_dir_merge_list automations/
climate:
config:
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
history:
http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 192.168.10.0/24
ios:
map:
mobile_app:
sun:
system_health:
webhook:

############################################################################
# Lovelace Configuration
############################################################################

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js 
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module
    - url: /hacsfiles/ha-sankey-chart/ha-sankey-chart.js
      type: module
    - url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js
      type: module
    - url: /hacsfiles/room-card/room-card.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js 
      type: module
    - url: /hacsfiles/bar-card/bar-card.js 
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js 
      type: module