---
homeassistant:
  name: Casa Lani
  latitude: !env_var HASS_LATITUDE
  longitude: !env_var HASS_LONGITUDE
  elevation: !env_var HASS_ELEVATION
  unit_system: metric
  time_zone: Europe/Berlin
  # Customization file
  customize: !include_dir_merge_named customizations/
  # Load packages
  legacy_templates: true
  packages: !include_dir_named packages
  external_url: "https://home.casalani.de"
  internal_url: "https://home.casalani.de"

############################################################################
# Configuration
############################################################################

automation: !include_dir_merge_list automations/
backup:
#binary_sensor: !include_dir_merge_list binary_sensor/
climate:
config:
discovery:
  ignore:
    - google_cast
frontend:
  themes: !include_dir_merge_named themes
http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - !env_var HASS_TRUSTED_NETWORK_1
    - !env_var HASS_TRUSTED_NETWORK_2
    - !env_var HASS_TRUSTED_NETWORK_3
ios:
map:
mobile_app:
# octoprint:
#   host: !secret octoprint_host
#   api_key: !secret octoprint_api
system_health:
webhook:

############################################################################
# Lovelace Configuration
############################################################################

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js 
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module