---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
# kiosk_mode:
#   hide_header: true

title: Casa Lani
views:
  - !include lovelace/home.yaml
  - !include lovelace/livingroom.yaml
  - !include lovelace/office.yaml
  - !include lovelace/bathroom.yaml
  - !include lovelace/kitchen.yaml
  - !include lovelace/hallway.yaml
  - !include lovelace/bedroom.yaml
  - !include lovelace/vacuum.yaml
  - !include lovelace/car.yaml
  - !include lovelace/energy.yaml
  - !include lovelace/sankey.yaml
