---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.

title: Casa Lani
views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/livingroom.yaml
  - !include lovelace/views/office.yaml
  - !include lovelace/views/kitchen.yaml
  - !include lovelace/views/bathroom.yaml
  - !include lovelace/views/bedroom.yaml
  - !include lovelace/views/hallway.yaml
  - !include lovelace/views/cellar.yaml
  - !include lovelace/views/batteries.yaml
  - !include lovelace/views/weather.yaml
  - !include lovelace/views/energy.yaml

button_card_templates:
  header:
    styles:
      card:
        - background-color: "#EBF4FC"
        - box-shadow: none
        - border-radius: 0%
        - padding: 0%
        - color: ivory
        - font-size: 10px
        - text-shadow: 0px 0px 0px black
        - text-transform: capitalize
      icon:
        - width: 15%
        - margin-top: 0%
        - margin-left: 0%
        - color: white
      name:
        - font-size: 16px
        - color: "#253B56"
        - text-transform: capitalize
        - justify-self: start
        - margin-left: 1%
        - font-family: avenir
  standard_button:
    styles:
      card:
        - font-size: 10px
      icon:
        - width: 30%
      name:
        - font-size: 12px
        - color: "#6A7889"
        - font-family: avenir
      state:
        - justify-self: start
        - font-size: 10px
        - padding: 0px 5px
        - color: "#6A7889"
        - font-family: avenir
