---
- alias: Living room lightning
  trigger:
    - platform: state
      entity_id: input_boolean.evening_lightning_default
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.media
    - service: scene.turn_on
      entity_id: scene.Abendbeleuchtung
