---
- alias: Media lightning
  trigger:
    - platform: state
      entity_id: input_boolean.media
      to: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.evening_lightning_default
    - service: scene.turn_on
      entity_id: scene.Movietime

- alias: Media lighting when plex
  trigger:
    - platform: state
      entity_id: media_player.jellyfin_sonytv
      to: "playing"
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.media

- alias: Media lighting after plex
  trigger:
    - platform: state
      entity_id: media_player.jellyfin_sonytv
      from: "playing"
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.evening_lightning_default
