---
- id: 'Tesla001'
  alias: Tesla - Start charging above 2kw
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.pv_wr_pc_grid_power
    below: '-1000'
#value to be adapted based on your solar capacity & charging rate
    for: 00:00:20
#adding a 'for' duration condition to avoid start on short sunbursts, if you want to avoid multiple on/offs you may increase that duration
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.teqqcar_location_tracker
          state: home
      #making sure this only activates when the Tesla is actually at home
        - condition: state
          entity_id: binary_sensor.teqqcar_charger_sensor
          state: 'on'
        - condition: state
          entity_id: switch.teqqcar_charger_switch
          state: 'off'
  #avoid a loop where the automation would try to turn on a switch that's already on
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.teqqcar_charger_switch
  mode: single

- alias: Adjust charging speed
  trigger:
  - platform: time_pattern
    minutes: '/1'
    seconds: 00
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: switch.teqqcar_charger_switch
          state: 'on'
        - condition: state
          entity_id: device_tracker.teqqcar_location_tracker
          state: home
  action:
    service: script.adjust_tesla_charging

- id: 'Tesla002'
  alias: Tesla - Couper charge si consommation trop élevée (>1500)
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.pv_wr_pc_home_power_from_battery
    above: '1500'
    for: 00:01:00
#adding a 'for' duration condition to avoid stop on every small cloud, if you want to avoid multiple on/offs you may increase that duration
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: device_tracker.teqqcar_location_tracker
          state: home
      #making sure this only activates when the Tesla is actually at home
        - condition: numeric_state
          entity_id: sensor.teqqcar_charging_rate_sensor
          above: '2'
      #making sure this only activates when the Tesla is actually charging: using the charging rate value seemed more stable than the state of the switch
        - condition: not
          conditions:
          - condition: state
            entity_id: switch.teqqcar_maxrange_switch
            state: 'on'
#"misusing" the Max Range switch to force charging even if conditions are not optimal, this switch is used in different automations
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.teqqcar_charger_switch
  mode: single