---
# Window automation
- alias: Heizung aus bei offenem Fenster
  trigger:
    platform: state
    entity_id: binary_sensor.bs_br_window
    to: 'on'
  action:
    service: climate.set_temperature
    entity_id: climate.trv_bathroom
    data:
      temperature: 18

- alias: Heizung an bei geschlossenem Fenster
  trigger:
    platform: state
    entity_id: binary_sensor.bs_br_window
    to: 'off'
  action:
    service: climate.set_temperature
    entity_id: climate.trv_bathroom
    data:
      temperature: 21

# Preheat Bathroom
- alias: Bathroom - preheat
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: 'wakeup'
  action:
    service: climate.set_temperature
    entity_id: climate.trv_bathroom
    data:
      temperature: 28

- alias: Bathroom - preheat finish
  trigger:
    platform: state
    entity_id: input_select.home_mode
    from: 'wakeup'
    to: 'home'
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.trv_bathroom
      temperature: 21

- alias: Bathroom - away
  trigger:
    platform: state
    entity_id: input_select.home_mode
    from: 'wakeup'
    to: 'away'
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.trv_bathroom
      temperature: 18

# General Bathroom Heating
- alias: Bathroom - Adjust temp above 25C
  trigger:
    platform: time_pattern
    hours: "/1"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - input_select.home_mode
        state: 'home'
      - condition: numeric_state
        entity_id: sensor.temperature_bathroom
        above: '25'
  action:
    - service: climate.set_temperature
      entity_id:
        - climate.trv_bathroom
      data:
        temperature: 21

- alias: Bathroom - Adjust temp above 23C
  trigger:
    platform: time_pattern
    hours: "/1"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - input_select.home_mode
        state: 'home'
      - condition: numeric_state
        entity_id: sensor.temperature_bathroom
        above: '25'
  action:
    - service: climate.set_temperature
      entity_id:
        - climate.trv_bathroom
      data:
        temperature: 22

- alias: Bathroom - Adjust temp below 20C
  trigger:
    platform: time_pattern
    hours: "/1"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - input_select.home_mode
        state: 'home'
      - condition: numeric_state
        entity_id: sensor.temperature_bathroom
        below: '20'
  action:
    - service: climate.set_temperature
      entity_id:
        - climate.trv_bathroom
      data:
        temperature: 23
