---
# Window automation
- alias: Heizung aus bei offenem Fenster
  trigger:
    platform: state
    entity_id: binary_sensor.bs_br_window_contact
    to: 'on'
  action:
    service: climate.set_temperature
    entity_id: climate.trv_bathroom
    data:
      temperature: 18

- alias: Heizung an bei geschlossenem Fenster
  trigger:
    platform: state
    entity_id: binary_sensor.bs_br_window_contact
    to: 'off'
  action:
    service: climate.set_temperature
    entity_id: climate.trv_bathroom
    data:
      temperature: 21

# Preheat Bathroom
- alias: Bathroom - preheat
  trigger:
    platform: state
    entity_id: sensor.house_status
    to: 'wakeup'
  action:
    - delay:
        minutes: 1
    - service: climate.set_temperature
      entity_id: climate.trv_bathroom
      data:
        temperature: 28

- alias: Bathroom - preheat finish
  trigger:
    platform: state
    entity_id: sensor.house_status
    from: 'wakeup'
    to: 'home'
  action:
    service: climate.set_temperature
    data:
      entity_id: climate.trv_bathroom
      temperature: 21
