---
- alias: Climate - Heat at morning
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: 'wakeup'
  action:
    service: climate.set_temperature
    entity_id: group.climate
    data:
      temperature: 23

- alias: Climate - Turn down on leaving home
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: 'away'
  action:
    service: climate.set_temperature
    entity_id: group.climate
    data:
      temperature: 21

- alias: Climate - Turn up on ariving home
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: 'home'
  action:
    service: climate.set_temperature
    entity_id: group.climate
    data:
      temperature: 23

- alias: Climate - Turn down for sleeping
  trigger:
    platform: state
    entity_id: input_select.home_mode
    to: 'sleep'
  action:
    service: climate.set_temperature
    entity_id: group.climate
    data:
      temperature: 21