---
# Window automation
- alias: heating off for kitchen window
  trigger:
    platform: state
    entity_id: binary_sensor.bs_ki_window
    to: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.trv_kitchen
        temperature: 18
        hvac_mode: heat

- alias: heating on for kitchen window
  trigger:
    platform: state
    entity_id: binary_sensor.bs_ki_window
    to: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.trv_kitchen
        temperature: 23
        hvac_mode: heat

# Adjust room temperature
- alias: Kitchen - Adjust temp above 25C
  trigger:
    platform: time_pattern
    hours: "/1"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - input_select.home_mode
        state: 'home'
      - condition: numeric_state
        entity_id: sensor.temperature_kitchen
        above: '26'
  action:
    - service: climate.set_temperature
      entity_id:
        - climate.trv_kitchen
      data:
        temperature: 21

- alias: Kitchen - Adjust temp above 24C
  trigger:
    platform: time_pattern
    hours: "/1"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - input_select.home_mode
        state: 'home'
      - condition: numeric_state
        entity_id: sensor.temperature_kitchen
        above: '24'
  action:
    - service: climate.set_temperature
      entity_id:
        - climate.trv_kitchen
      data:
        temperature: 22

- alias: Kitchen - Adjust temp below 22C
  trigger:
    platform: time_pattern
    hours: "/1"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - input_select.home_mode
        state: 'home'
      - condition: numeric_state
        entity_id: sensor.temperature_kitchen
        below: '22'
  action:
    - service: climate.set_temperature
      entity_id:
        - climate.trv_kitchen
      data:
        temperature: 25
