---
# Window automation
- alias: heating off for kitchen window
  trigger:
    platform: state
    entity_id: binary_sensor.bs_ki_window
    to: 'on'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.trv_kitchen
        temperature: 18
        hvac_mode: heat

- alias: heating on for kitchen window
  trigger:
    platform: state
    entity_id: binary_sensor.bs_ki_window
    to: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.trv_kitchen
        temperature: 23
        hvac_mode: heat