---
# Adjust room temperature

- alias: office cb - set temperature
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.temperature_office
  condition:
    condition: state
    entity_id: climate.trv_cb_office
    state: 'heat'
  action:
    - device_id: 905b144d25c65bd220d06cfad1ae2846
      domain: select
      entity_id: select.trv_cb_office_sensor
      type: select_option
      option: external
    - delay:
        hours: 0
        minutes: 0
        seconds: 10
        milliseconds: 0
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/trv_cb_office/set/sensor_temp
        payload_template: >-
          {{ (states('sensor.temperature_office')|float(0)|round(1))
          }}

- alias: office pt - set temperature
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.temperature_office
  condition:
    condition: state
    entity_id: climate.trv_cb_office
    state: 'heat'
  action:
    - device_id: 6e6e99fca4e45938abc89f24bc547a97
      domain: select
      entity_id: select.trv_pt_office_sensor
      type: select_option
      option: external
    - delay:
        hours: 0
        minutes: 0
        seconds: 10
        milliseconds: 0
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/trv_pt_office/set/sensor_temp
        payload_template: >-
          {{ (states('sensor.temperature_office')|float(0)|round(1))
          }}

- id: "pVLhfOqB6IW6rdFx3ZDctntZvov8A44nlADJZrdkW60iFhLnGrX1BytB2Uo2Y0In"
  alias: Office - Turn off climate if Window open - CB
  trigger:
    - platform: state
      entity_id: binary_sensor.bs_of_cb_window_contact
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - sensor.weather_day
        state: 'normalday'
      - condition: state
        entity_id:
          - climate.trv_cb_office
        state: 'heat'
  action:
    service: climate.turn_off
    entity_id: climate.trv_cb_office

- id: "2PnyX9ffE74AxTlL9XNXS9cRn3AviR62eM9wjHeqDalRSOfljyzh41iGCDCdGhDr"
  alias: Office - Turn off climate if Window open - PT
  trigger:
    - platform: state
      entity_id: binary_sensor.bs_of_pt_window_contact
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - sensor.weather_day
        state: 'normalday'
      - condition: state
        entity_id:
          - climate.trv_pt_office
        state: 'heat'
  action:
    service: climate.turn_off
    entity_id: climate.trv_pt_office

- id: "kLqR3RyK74fnP4yOR0vgXy3LcHsmgNzaxCJ1NBcyagmo2DgBIux28Iqb1D1uVJIB"
  alias: Office - Turn on climate if Window is closed - CB
  trigger:
    - platform: state
      entity_id: binary_sensor.bs_of_cb_window_contact
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - sensor.weather_day
        state: 'normalday'
      - condition: state
        entity_id:
          - climate.trv_cb_office
        state: 'off'
  action:
    service: climate.turn_on
    target:
      entity_id: climate.trv_cb_office

- id: "KXZYJMpQ1rHFstz9WvvhBoXjsctjlbmp8lbJHvG6LrabpTyX2hCvbUypYzj1f3kI"
  alias: Office - Turn on climate if Window is closed - PT
  trigger:
    - platform: state
      entity_id: binary_sensor.bs_of_pt_window_contact
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - sensor.weather_day
        state: 'normalday'
      - condition: state
        entity_id:
          - climate.trv_pt_office
        state: 'off'
  action:
    service: climate.turn_on
    target:
      entity_id: climate.trv_pt_office