---
# Project information
site_name: Home Assistant Config
site_description: >-
  This repo is the current state of my home-assistant configuration
site_author: Christian Birkenbeul
site_url: https://cbirkenbeul.github.io/home-assistant-config/

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-name
repo_name: christianb/home-assistant-config
repo_url: https://github.com/christianb/home-assistant-config

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#edit-button
edit_uri: "edit/main/docs/src/"

# Configuration
theme:
  name: material

  # Static files
  static_templates:
    - 404.html

  # logo: https://raspbernetes.github.io/img/logo.svg
  # favicon: https://raspbernetes.github.io/img/logo.svg
  language: en

  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  icon:
    repo: fontawesome/brands/github

  font:
    text: Roboto
    code: Roboto Mono

  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#automatic-hiding
    - header.autohide
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking
    - navigation.tracking
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-sharing
    - search.share
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    - navigation.instant
    - navigation.sections
    - content.code.annotate

docs_dir: ../../docs/src/

extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#versioning
  version:
    provider: mike
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cbirkenbeul
    - icon: fontawesome/brands/linkedin
      link: https://au.linkedin.com/in/nathannial-allan-60a418104
    - icon: fontawesome/solid/sitemap
      link: https://www.teqqy.de
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#remove-generator
  generator: false

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#copyright-notice
copyright: Copyright &copy; 2022 Christian Birkenbeul

extra_css:
  - _static/custom.css

plugins:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#built-in-search
  - search
  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#revision-date-localized
  - git-revision-date-localized
  - autolinks
  - diagrams

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#google-analytics
# google_analytics:
#   - UA-XXXXXXXX-X
#   - auto

# https://www.mkdocs.org/user-guide/configuration/#markdown_extensions
markdown_extensions:
  - admonition
  - abbr
  - meta
  - md_in_html
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.tasklist
  - pymdownx.snippets:
      base_path:
        - ../../docs/src/
        - ../../docs/_includes/
        - docs/_includes/
      # auto_append:
      #   - abbreviations.md
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: index.md
  - General:
      - Software: general/software.md
      - Hardware: general/hardware.md
  # - Repository:
  #     - Semantic Commits: repository/semantic-git-messages.md
  #     - Folder Structure: repository/folder-structure.md
  # - Sidero & Talos:
  #     - Introduction: sidero/sidero-intro.md
  #     - Installation: sidero/sidero-install.md
  #     - Retrieve talosconfig: sidero/retrieve_talosconfig.md
  # - Diagrams:
  #     - Network Map: diagrams/network-map.md
  #     - Cluster Map: diagrams/cluster-map.md
  # - Cluster:
  #     - Bootstrap Workflow: cluster/bootstrap-workflow.md
  # - Applications:
  #     - k10: apps/k10.md
      # - Get Started: get-started/index.md
      # - Guides:
      #     - Installation: guides/installation.md
      #     - Sealed Secrets: guides/sealed-secrets.md
      #     - Mozilla SOPS: guides/mozilla-sops.md
      #     - Repository Structure: guides/repo-structure.md
      # - Designs:
      #     - Secret Management: designs/secret-management.md
      # - Hardware:
      #     - RockPis: hardware/pre-rockpi4c.md
      # - Network:
      #     - IP Allocation: network/ip-allocation.md
      #     - Certificates: network/certificates.md
      # - Contributing: contributing/index.md
      # - Sponsor: sponsor/index.md
      # - FAQ: faq/index.md
