---
- alias: Kellerbeleuchtung ein
  trigger:
    platform: state
    entity_id: binary_sensor.bs_hw_bm_door_contact
    to: 'on'
  action:
    service: light.turn_on
    entity_id:
      - light.li_bm_stairs
      - light.li_bm_hw

- alias: Kellerbeleuchtung aus
  trigger:
    platform: state
    entity_id: binary_sensor.bs_hw_bm_door_contact
    to: 'off'
  action:
    service: light.turn_off
    entity_id:
      - light.li_bm_stairs
      - light.li_bm_hw
