---
- alias: turn on flux integration
  trigger:
    - platform: time
      at: '23:00:00'
  condition:
    condition: state
    entity_id:
      - input_select.home_mode
    state: 'home'
  action:
    - service: switch.turn_on
      entity_id: switch.flux
