---
- alias: Wohnzimmerbeleuchtung bei Sonnenuntergang
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id:
      - input_select.home_mode
    state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.evening_lightning_default
    - service: switch.turn_on
      entity_id: switch.sw_hw_og_deko
    - service: switch.turn_on
      entity_id: switch.sw_of_cb_deko
