---
- alias: Light 2h before sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  condition:
    condition: state
    entity_id:
      - input_select.home_mode
    state: 'home'
  action:
    service: switch.turn_on
    entity_id: switch.sw_lr_deko
