---
- alias: turn on nightmode
  trigger:
    - platform: time
      at: '01:00:00'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.nightmode
    - service: input_boolean.turn_off
      entity_id: input_boolean.evening_lightning_default
    - service: input_boolean.turn_off
      entity_id: input_boolean.media
    - delay: '00:00:30'
    - service: input_boolean.turn_off
      entity_id: input_boolean.nightmode
    - service: mqtt.publish
      data:
        topic: house/weather/daycondition
        payload: normalday
        retain: true
    - service: mqtt.publish
      data:
        topic: house/house/status
        payload: sleep
        retain: true

- alias: turn off lights
  trigger:
    - platform: state
      entity_id: input_boolean.nightmode
  action:
    - service: light.turn_off
      entity_id: all
    - service: switch.turn_off
      entity_id:
        - switch.sw_hw_og_deko
        - switch.sw_of_cb_deko
        - switch.flux
        - switch.sw_dr_deko
