---
- alias: turn on nightmode
  trigger:
    - platform: time
      at: '01:00:00'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.nightmode
    - service: climate.set_temperature
      entity_id:
        - climate.trv_office_cb_thermostat
        - climate.trv_office_pt_thermostat
        - climate.trv_bathroom
        - climate.trv_kitchen
      data:
        temperature: 21
    - service: input_boolean.turn_off
      entity_id: input_boolean.evening_lightning_default
    - service: input_boolean.turn_off
      entity_id: input_boolean.media

- alias: turn off nightmode
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.nightmode

- alias: turn off lights
  trigger:
    - platform: state
      entity_id: input_boolean.nightmode
  action:
    - service: light.turn_off
      entity_id: all
    - service: switch.turn_off
      entity_id:
        - switch.sw_hw_og_deko
        - switch.sw_lr_deko
        - switch.sw_of_cb_deko
        - switch.flux
