---
- alias: Turn light of at away
  trigger:
    platform: state
    entity_id: group.devices
    from: 'home'
    to: 'not_home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id:
        - switch.sw_hw_og_deko
        - switch.sw_lr_deko
        - switch.sw_of_cb_deko
    - service: input_boolean.turn_off
      entity_id: input_boolean.evening_lightning_default

- alias: Turn lights on when back home after sunset
  trigger:
    platform: state
    entity_id: group.devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: sun
    after: sunset
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.evening_lightning_default
