---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   14.01.2022
#   @package        :   Appliances
#   @description    :   Make dump dryer and washer smarter
###############################################################################

# Sensors
sensor:
  - platform: mqtt
    name: "Washer Status"
    state_topic: "house/washer/status"

  - platform: mqtt
    name: "Dryer Status"
    state_topic: "house/dryer/status"

# Automations
automation:
  - id: "44zqeh37GFMyDybWR8v73fQj8HXeYpdXcPAwVxUmCa4ybD9gdkRrA2zXHecWS2BF"
    alias: Set dryer Status to running
    trigger:
      platform: numeric_state
      entity_id: sensor.trockner_electricity_power
      above: 5
    action:
      - service: mqtt.publish
        data:
          topic: house/dryer/status
          payload: running
          retain: true

  - id: "yhe3ux5QGuhJ5PX4s5wdAdS7BXZwJw8PFjwwsqRAtsPcwFH6WF2uevG8MPKz2kya"
    alias: Set dryer Status to finish
    trigger:
      platform: numeric_state
      entity_id: sensor.trockner_electricity_power
      below: 3
      for:
        minutes: 5
    condition:
      - condition: state
        entity_id: sensor.dryer_status
        state: running
    action:
      - service: mqtt.publish
        data:
          topic: house/dryer/status
          payload: complete
          retain: true
      - service: script.turn_on
        entity_id: script.dryer_finished_notification_push

  - id: "w9fvMY3fAtBqGAg6eQJqeEPHAwjsz3YNBGcDL74xKkz4QdwyZN25LsPw32fHuN49"
    alias: Set dryer status to idle
    trigger:
      platform: state
      entity_id: binary_sensor.bs_hw_bm_door_contact
      to: 'on'
    condition:
      condition: state
      entity_id: sensor.dryer_status
      state: complete
    action:
      - service: mqtt.publish
        data:
          topic: house/dryer/status
          payload: idle
          retain: true

  - id: "m66g2sKT5AA8LabCRb92hdAxDxMWR2yWMGSJfDMB8XWhWCyjhhBM38ZThMtwk7FL"
    alias: Set washer Status to running
    trigger:
      platform: numeric_state
      entity_id: sensor.waschmaschine_electricity_power
      above: 5
    condition:
      condition: state
      entity_id: sensor.washer_status
      state: idle
    action:
      - service: mqtt.publish
        data:
          topic: house/washer/status
          payload: running
          retain: true

  - id: "JegBfnJsYFyw4DWEaChdRd3BQwBJVb65sMLQXPWbHVAndETWnwxNynz9CEKxBVMS"
    alias: Set washer Status to finish
    trigger:
      platform: numeric_state
      entity_id: sensor.waschmaschine_electricity_power
      below: 3
      for:
        minutes: 5
    condition:
      - condition: state
        entity_id: sensor.washer_status
        state: running
    action:
      - service: mqtt.publish
        data:
          topic: house/washer/status
          payload: complete
          retain: true
      - service: script.turn_on
        entity_id: script.washer_finished_notification_push

  - id: "SnVBxwq2VZbAg3xwqjcG5LDP7tZngh8yQqvqgpnkbyrEmfySMJxmfj5rne74kTAM"
    alias: Set washer status to idle
    trigger:
      platform: state
      entity_id: binary_sensor.bs_hw_bm_door_contact
      to: 'on'
    condition:
      - condition: state
        entity_id: sensor.washer_status
        state: complete
    action:
      - service: mqtt.publish
        data:
          topic: house/washer/status
          payload: idle
          retain: true

# Power Cicle
utility_meter:
  washer_energy_daily:
    source: sensor.waschmaschine_electric_kwh_value
    cycle: daily

  dryer_energy_daily:
    source: sensor.trockner_electric_kwh_value
    cycle: daily

script:
  dryer_finished_notification_push:
    sequence:
    - repeat:
        while:
          - condition: state
            entity_id: sensor.dryer_status
            state: 'complete'
        sequence:
        - delay:
            minutes: 10
        - service: script.simplified_dryer_push

  simplified_dryer_push:
    sequence:
    - condition: state
      entity_id: group.devices
      state: 'home'
    - condition: state
      entity_id: sensor.dryer_status
      state: complete
    - service: notify.mobile_app_clios_iphone
      data:
        message: "Test!"

  washer_finished_notification_push:
    sequence:
    - repeat:
        while:
          - condition: state
            entity_id: sensor.washer_status
            state: 'complete'
        sequence:
        - delay:
            minutes: 10
        - service: script.simplified_washer_push

  simplified_washer_push:
    sequence:
    - condition: state
      entity_id: group.devices
      state: 'home'
    - condition: state
      entity_id: sensor.washer_status
      state: complete
    - service: notify.mobile_app_clios_iphone
      data:
        message: "Test!"