---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   14.01.2022
#   @package        :   Appliances
#   @description    :   Make dump dryer and washer smarter
###############################################################################

# Sensors
sensor:

input_select:
  washer:
    name: Status Waschmaschine
    options:
      - idle
      - running
      - complete
    initial: idle
    icon: mdi:washing-machine

  dryer:
    name: Status Trockner
    options:
      - idle
      - running
      - complete
    initial: idle
    icon: mdi:tumble-dryer

# Automations
automation:
  - id: "44zqeh37GFMyDybWR8v73fQj8HXeYpdXcPAwVxUmCa4ybD9gdkRrA2zXHecWS2BF"
    alias: Set dryer Status to running
    trigger:
      platform: numeric_state
      entity_id: sensor.trockner_electricity_power
      above: 5
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.dryer
        data:
          option: running

  - id: "yhe3ux5QGuhJ5PX4s5wdAdS7BXZwJw8PFjwwsqRAtsPcwFH6WF2uevG8MPKz2kya"
    alias: Set dryer Status to finish
    trigger:
      platform: numeric_state
      entity_id: sensor.trockner_electricity_power
      below: 3
      for:
        minutes: 5
    condition:
      - condition: state
        entity_id: input_select.dryer
        state: running
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.dryer
        data:
          option: complete
      - service: script.turn_on
        entity_id: script.dryer_finished_notification_push

  - id: "w9fvMY3fAtBqGAg6eQJqeEPHAwjsz3YNBGcDL74xKkz4QdwyZN25LsPw32fHuN49"
    alias: Set dryer status to idle
    trigger:
      platform: state
      entity_id: binary_sensor.bs_hw_bm_door_contact
      to: "on"
    condition:
      condition: state
      entity_id: input_select.dryer
      state: complete
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.dryer
        data:
          option: idle

  - id: "m66g2sKT5AA8LabCRb92hdAxDxMWR2yWMGSJfDMB8XWhWCyjhhBM38ZThMtwk7FL"
    alias: Set washer Status to running
    trigger:
      platform: numeric_state
      entity_id: sensor.waschmaschine_electricity_power
      above: 5
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.washer
          state: idle
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.washer
        data:
          option: running

  - id: "JegBfnJsYFyw4DWEaChdRd3BQwBJVb65sMLQXPWbHVAndETWnwxNynz9CEKxBVMS"
    alias: Set washer Status to finish
    trigger:
      platform: numeric_state
      entity_id: sensor.waschmaschine_electricity_power
      below: 3
      for:
        minutes: 5
    condition:
      - condition: state
        entity_id: input_select.washer
        state: running
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.washer
        data:
          option: complete
      - service: script.turn_on
        entity_id: script.washer_finished_notification_push

  - id: "SnVBxwq2VZbAg3xwqjcG5LDP7tZngh8yQqvqgpnkbyrEmfySMJxmfj5rne74kTAM"
    alias: Set washer status to idle
    trigger:
      platform: state
      entity_id: binary_sensor.bs_hw_bm_door_contact
      to: "on"
    condition:
      - condition: state
        entity_id: input_select.washer
        state: complete
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.washer
        data:
          option: idle

# Power Cicle
utility_meter:
  washer_energy_daily:
    source: sensor.waschmaschine_electric_kwh_value
    cycle: daily

  dryer_energy_daily:
    source: sensor.trockner_electric_kwh_value
    cycle: daily

script:
  dryer_finished_notification_push:
    sequence:
    - repeat:
        while:
          - condition: state
            entity_id: input_select.dryer
            state: "complete"
        sequence:
        - delay:
            minutes: 10
        - service: script.simplified_dryer_push

  simplified_dryer_push:
    sequence:
    - condition: state
      entity_id: group.devices
      state: "home"
    - condition: state
      entity_id: input_select.dryer
      state: "complete"
    - service: notify.telegram_group
      data:
        message: "Der Trockner ist bereit zum Ausräumen."

  washer_finished_notification_push:
    sequence:
    - repeat:
        while:
          - condition: state
            entity_id: input_select.washer
            state: "complete"
        sequence:
        - delay:
            minutes: 10
        - service: script.simplified_washer_push

  simplified_washer_push:
    sequence:
    - condition: state
      entity_id: group.devices
      state: "home"
    - condition: state
      entity_id: input_select.washer
      state: "complete"
    - service: notify.telegram_group
      data:
        message: "Die Waschmaschine ist fertig. Bitte zeitnah ausräumen."