---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   14.01.2022
#   @package        :   Appliances
#   @description    :   Make dump dryer and washer smarter
###############################################################################

# Sensors
sensor:
  - platform: mqtt
    name: "Washer Status"
    state_topic: "house/washer/status"
  - platform: mqtt
    name: "Dryer Status"
    state_topic: "house/dryer/status"


# Finish state
input_boolean:
  washer_finish:
    name: Waschmaschine fertig
    initial: off

  dryer_finish:
    name: Trocker fertig
    initial: off

# States of appliances
input_select:
  washer_mode:
    name: Status Waschmaschine
    options:
      - idle
      - running
      - finish
    initial: idle
    icon: mdi:washing-machine

  dryer_mode:
    name: Status Trockner
    options:
      - idle
      - running
      - finish
    initial: idle
    icon: mdi:tumble-dryer

# Automations
automation:
  - alias: Set dryer Status to running
    trigger:
      platform: numeric_state
      entity_id: sensor.trockner_electricity_power
      value_template: '{{ states.sensor.trockner_electricity_power.state }}'
      above: 5
      for:
        minutes: 1
    action:
      - service: mqtt.publish
        data:
          topic: house/dryer/status
          payload: running
          retain: true

  - alias: Set dryer Status to finish
    trigger:
      platform: numeric_state
      entity_id: sensor.trockner_electricity_power
      value_template: '{{ states.sensor.trockner_electricity_power.state }}'
      below: 3
      for:
        minutes: 5
    condition:
      condition: state
      entity_id: input_select.dryer_mode
      state: running
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.dryer_finish
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_mode
          option: finish

  - alias: Set dryer status to idle
    trigger:
      platform: state
      entity_id: binary_sensor.bs_hw_bm_door_contact
      to: 'on'
    condition:
      condition: state
      entity_id: input_select.dryer_mode
      state: finish
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.dryer_finish
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_mode
          option: idle

  - alias: Set washer Status to running
    trigger:
      platform: numeric_state
      entity_id: sensor.waschmaschine_electricity_power
      value_template: '{{ states.sensor.waschmaschine_electricity_power.state }}'
      above: 1
      for:
        minutes: 1
    condition:
      condition: state
      entity_id: input_select.washer_mode
      state: idle
    action:
      - service: mqtt.publish
        data:
          topic: house/washer/status
          payload: running
          retain: true

  - alias: Set washer Status to finish
    trigger:
      platform: numeric_state
      entity_id: sensor.waschmaschine_electricity_power
      value_template: '{{ states.sensor.waschmaschine_electricity_power.state }}'
      below: 3
      for:
        minutes: 5
    condition:
      - condition: state
        entity_id: sensor.washer_status
        state: running
    action:
      #- service: input_boolean.turn_on
      #  entity_id: input_boolean.washer_finish
      - service: mqtt.publish
        data:
          topic: house/washer/status
          payload: finnish
          retain: true
      - service: script.turn_on
        entity_id: script.washer_finished_notification_push

  - alias: Set washer status to idle
    trigger:
      platform: state
      entity_id: binary_sensor.bs_hw_bm_door_contact
      to: 'on'
    condition:
      - condition: state
        entity_id: sensor.washer_status
        state: finish
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.washer_finish
      - service: mqtt.publish
        data:
          topic: house/washer/status
          payload: idle
          retain: true

# Notifications
alert:
  trockner:
    name: Trockner ist fertig
    done_message: Danke fürs ausschalten.
    entity_id: input_boolean.dryer_finish
    state: "on"
    repeat: 10
    can_acknowledge: true
    skip_first: true
    notifiers:
      - petra

  waschmaschine:
    name: Waschmaschine ist fertig
    done_message: Danke fürs ausschalten.
    entity_id: input_boolean.washer_finish
    state: "on"
    repeat: 10
    can_acknowledge: true
    skip_first: true
    notifiers:
      - petra

# Power Cicle
utility_meter:
  washer_energy_daily:
    source: sensor.waschmaschine_electric_kwh_value
    cycle: daily

  dryer_energy_daily:
    source: sensor.trockner_electric_kwh_value
    cycle: daily

script:
  washer_finished_notification_push:
    sequence:
    - repeat:
        while:
          - condition: state
            entity_id: sensor.washer_status
            state: 'finish'
        sequence:
        - delay:
            minutes: 10
        - service: script.simplified_washer_push

  simplified_washer_push:
    sequence:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: sensor.washer_status
      state: finish
    - service: notify.mobile_app_cliosiphone
      data:
        message: "Test!"