---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   03.02.2024
#   @package        :   awtrix
#   @description    :   Send information to Ulanzi TC001
###############################################################################

# Automation
automation:
  - id: "jdrqaxu2n6i5p8yvle41bgs0wotz9m3k"
    trigger:
      - platform: time_pattern
        seconds: /30
    condition:
      - condition: numeric_state
        entity_id: sensor.pv_prod_ges
        above: 10
    action:
      - service: mqtt.publish
        data_template:
          qos: "2"
          retain: false
          #an deine ID anpassen!
          topic: awtrix_f53d30/custom/pvproduction
          payload_template: >-
            {% if states('sensor.pv_prod_ges')|float <= 100 %}
              { "text": "{{ states.sensor.pv_prod_ges.state }}", "icon": "91",  "color": "FFFFFF"}
            {% elif states('sensor.pv_prod_ges')|float <= 500 %}
              { "text": "{{ states.sensor.pv_prod_ges.state }}", "icon": "876",  "color": "e74c3c"}
            {% elif states('sensor.pv_prod_ges')|float <= 2000 %}
              { "text": "{{ states.sensor.pv_prod_ges.state }}", "icon": "876",  "color": "f1c40f"}
            {% elif states('sensor.pv_prod_ges')|float <= 4000 %}
              { "text": "{{ states.sensor.pv_prod_ges.state }}", "icon": "876",  "color": "2ecc71"}
            {% else %}
              { "text": "{{ states.sensor.pv_prod_ges.state }}", "icon": "515",  "color": "27ae60"}
            {% endif %}

  - id: "febr8q5hz3ogaj26t0pu1li7cmkwv9sx"
    trigger:
      platform: numeric_state
      entity_id: sensor.pv_prod_ges
      below: 10
    action:
      - service: mqtt.publish
        data:
          topic: "awtrix_f53d30/custom/pvproduction"
          payload: ""
          retain: true

  - id: "nt6ef8rpzsj75i01q392xlwdvycugkmb"
    trigger:
      - platform: time_pattern
        seconds: /30      
    action:
      - service: mqtt.publish
        data_template:
          qos: "2"
          retain: false
          #an deine ID anpassen!
          topic: awtrix_f53d30/custom/housebattery
          payload_template: >-
            {% if states('sensor.pv_wr_pc_battery_soc')|float <= 15 %}
              { "text": "{{ states.sensor.pv_wr_pc_battery_soc.state }} %", "icon": "3697",  "color": "FFFFFF"}
            {% elif states('sensor.pv_wr_pc_battery_soc')|float <= 35 %}
              { "text": "{{ states.sensor.pv_wr_pc_battery_soc.state }} %", "icon": "3701",  "color": "d35400"}
            {% elif states('sensor.pv_wr_pc_battery_soc')|float <= 55 %}
              { "text": "{{ states.sensor.pv_wr_pc_battery_soc.state }} %", "icon": "3699",  "color": "f39c12"}
            {% elif states('sensor.pv_wr_pc_battery_soc')|float <= 75 %}
              { "text": "{{ states.sensor.pv_wr_pc_battery_soc.state }} %", "icon": "3703",  "color": "f39c12"}
            {% elif states('sensor.pv_wr_pc_battery_soc')|float <= 90 %}
              { "text": "{{ states.sensor.pv_wr_pc_battery_soc.state }} %", "icon": "3695",  "color": "2ecc71"}
            {% else %}
              { "text": "{{ states.sensor.pv_wr_pc_battery_soc.state }} %", "icon": "3693",  "color": "27ae60"}
            {% endif %}

  - id: "89vtplahf1msz345dxic6qn0k2guejyr"
    trigger:
      - platform: time_pattern
        seconds: /30
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.teqqcar_location_tracker
            state: home
          - condition: state
            entity_id: binary_sensor.teqqcar_charging
            state: "on"      
    action:
      - service: mqtt.publish
        data_template:
          qos: "2"
          retain: true
          #an deine ID anpassen!
          topic: awtrix_f53d30/custom/teslacharging
          payload_template: >-
              { "text": "{{ states.sensor.teqqcar_charger_power.state }}kw @ {{ states.sensor.teqqcar_battery.state }} %", "icon": "53536",  "color": "FFFFFF"}

  - id: "febr0q5hz3ogaj26e0pu1li7cmkwv9sx"
    trigger:
      platform: state
      entity_id: binary_sensor.teqqcar_charging
      to: "off"
    condition:
      - condition: state
        entity_id: device_tracker.teqqcar_location_tracker
        state: "home"      
    action:
      - service: mqtt.publish
        data:
          topic: "awtrix_f53d30/custom/teslacharging"
          payload: ""
          retain: true