---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   23.04.2022
#   @package        :   Integrations
#   @description    :   Combine Integrations to one file
###############################################################################

# Binary Sensors
binary_sensor:
  - platform: workday
    country: DE

# Flux Light Component and Automation
switch:
  - platform: flux
    lights:
      - light.bodenlampe
      - light.couch
    start_time: '21:00'
    stop_time: '01:00'
    brightness: 200
    disable_brightness_adjust: true

automation:
  - id: "AUs7qvfFUApLhFCzAkwdVQ9JzUMfn4tFQfiHcX9kyoeXVasyi3tkdnqJ3VtK4E2b"
    alias: Light - Turn on flux custom component
    trigger:
      - platform: time
        at: '23:00:00'
    action:
      - service: switch.turn_on
        entity_id: switch.flux