---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   08.11.2022
#   @package        :   gitops
#   @description    :   Push git changes to home assistant
###############################################################################

automation:
  - id: update_config_github_push_event
    alias: Update Configuration on Github Push Event

    trigger:
    - platform: webhook
      webhook_id: update_config

    action:
    - service: shell_command.update_config
    - service: homeassistant.restart

shell_command:
  update_config: cd /config && git pull