---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   05.06.2022
#   @package        :   Light
#   @description    :   All lights automation
###############################################################################

automation:
# Automations for basement
  - id: "We9s3rderooyvehppbfHhpZ2DKpGq7vUNgnngdtNQsNuLeXuNDEWYNzNorACeaj7"
    alias: Light - Basement on
    trigger:
      platform: state
      entity_id: binary_sensor.bs_hw_bm_door_contact
      to: 'on'
    action:
      service: light.turn_on
      entity_id:
        - light.li_bm_stairs
        - light.li_bm_hw

  - id: "cFPAsWaQ8bcAvPrP8Agm7BfA6Lxi8bHuR7eRhMhHvmhvKLkr6JNCBPVERDG44PU2"
    alias: Light - Basement off
    trigger:
      platform: state
      entity_id: binary_sensor.bs_hw_bm_door_contact
      to: 'off'
    action:
      service: light.turn_off
      entity_id:
        - light.li_bm_stairs
        - light.li_bm_hw

# Automations based on sun
  - id: "DE3BCwN9ArLNbHRggfoDg223FnMApomF7pVtP6pBPWTfXw3fGv3fCfZpEPsjNWMh"
    alias: Light - Turn on some light before sunset
    trigger:
      platform: sun
      event: sunset
      offset: "-01:00:00"
    condition:
      condition: state
      entity_id: sensor.house_status
      state: home
    action:
      service: switch.turn_on
      entity_id: switch.sw_lr_deko

  - id: "fLeoPM2GZVCbsTeVpGenmbhowfsNmjYxEVbt6tBpzTpbqukpzxHd36JGNFT8cQK6"
    alias: Light - Sunset
    trigger:
      platform: sun
      event: sunset
    condition:
      condition: state
      entity_id: sensor.house_status
      state: home
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.evening_lightning_default
      - service: switch.turn_on
        entity_id: switch.sw_hw_og_deko
      - service: switch.turn_on
        entity_id: switch.sw_of_cb_deko

# Automations based on presence
  - id: "LNb9FtPZEdtFzLxz8XEY8yri6PEGFBktBvCbpbJ72DiVciPQK7rp2P2XDrbnktYp"
    alias: Light - Turn off lights if all away
    trigger:
      platform: state
      entity_id: group.devices
      from: 'home'
      to: 'not_home'
    action:
      - service: light.turn_off
        entity_id: all
      - service: switch.turn_off
        entity_id:
          - switch.sw_hw_og_deko
          - switch.sw_lr_deko
          - switch.sw_of_cb_deko
          - switch.flux
      - service: input_boolean.turn_off
        entity_id: input_boolean.evening_lightning_default

  - id: "xAVMZyFE45rS9Wc9LGEKpR5xMB7PPK7U7_pSMEvK8hQng3l6ir6biXCo_UmofqXX"
    alias: Light - Turn on lights after sunset
    trigger:
      platform: state
      entity_id: group.devices
      from: 'not_home'
      to: 'home'
    condition:
      condition: sun
      after: sunset
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.evening_lightning_default

# Scenes
scene:
  - name: Movietime
    icon: mdi:movie
    entities:
      light.couch: 
        state: 'off'
      light.wz_decke: 
        state: 'off'
      light.bodenlampe:
        state: 'on'
        brightness: 80
        rgb_color: [0, 255, 0]

  - name: Abendbeleuchtung
    icon: mdi:television-ambient-light
    entities:
      light.couch:
        state: 'on'
        brightness: 200
        rgb_color: [255, 214, 170]
      light.wz_decke:
        state: 'off'
      light.bodenlampe:
        state: 'on'
        brightness: 200
        rgb_color: [255, 214, 170]
      switch.sw_hw_og_deko:
        state: 'on'
      switch.sw_lr_deko:
        state: 'on'
      switch.sw_of_cb_deko:
        state: 'on'
      switch.sw_dr_deko:
        state: 'on'

  - name: youtube
    icon: mdi:youtube
    entities:
      light.az_cb_decke:
        state: 'on'
        brightness: 127
        kelvin: 5600
      light.az_bloom:
        state: 'on'
        brightness: 255
        rgb_color: [255, 168, 1]
      light.keylight:
        state: 'on'

# Input Booleans
input_boolean:
  evening_lightning_default:
    name: Abendbeleuchtung
    initial: off
    icon: mdi:weather-sunset

  away_from_heating:
    name: Keine Heizung
    initial: off

  media:
    name: Media
    initial: off
    icon: mdi:movie

  nightmode:
    name: Nachtmodus
    initial: off
    icon: mdi:weather-night