---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   29.09.2023
#   @package        :   Light
#   @description    :   All lights automation
###############################################################################

light:
  - platform: group
    name: "Stairway Lights"
    entities:
      - light.hw_bottom
      - light.hw_center
      - light.hw_top  

automation:
  # Automations based on sun
  - id: "fLeoPM2GZVCbsTeVpGenmbhowfsNmjYxEVbt6tBpzTpbqukpzxHd36JGNFT8cQK6"
    alias: Light - Sunset
    trigger:
      platform: sun
      event: sunset
    condition:
      condition: state
      entity_id: sensor.house_status
      state: home
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.evening_lightning_default
      - service: switch.turn_on
        entity_id: switch.pg_hw_deco
      - service: switch.turn_on
        entity_id: light.li_of_cb_bloom

  # Automations based on presence
  - id: "LNb9FtPZEdtFzLxz8XEY8yri6PEGFBktBvCbpbJ72DiVciPQK7rp2P2XDrbnktYp"
    alias: Light - Turn off lights if all away
    trigger:
      platform: state
      entity_id: group.devices
      from: "home"
      to: "not_home"
    action:
      - service: light.turn_off
        entity_id: all
      - service: switch.turn_off
        entity_id:
          - switch.pg_hw_deco
          - switch.flux
      - service: input_boolean.turn_off
        entity_id: input_boolean.evening_lightning_default

  - id: "xAVMZyFE45rS9Wc9LGEKpR5xMB7PPK7U7_pSMEvK8hQng3l6ir6biXCo_UmofqXX"
    alias: Light - Turn on lights after sunset
    trigger:
      platform: state
      entity_id: group.devices
      from: "not_home"
      to: "home"
    condition:
      condition: sun
      after: sunset
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.evening_lightning_default

  ###############################################################################
  #   Stairway Lights
  ###############################################################################

  - id: "4H2sE7SdUwfjWSKyNIMef4cM0A1KqvIzFArXL1CzT1ywPT6kqIN3JOxhkshfBBbb"
    alias: Light - Turn on stair lights on motion"
    trigger:
      platform: state
      entity_id: binary_sensor.se_hw_og_motion_occupancy
      to: "on"
    condition:
      condition: numeric_state
      entity_id: sensor.se_hw_og_motion_illuminance_lux
      below: "10"
    action:
      - choose:
          - conditions: 
              - condition: time
                after: '22:00:00'
                before: '06:00:00'
            sequence:
              - service: light.turn_on
                data:
                  entity_id: light.stairway_lights
                  brightness: 1
              - delay:
                  seconds: 20
              - service: light.turn_off
                entity_id: light.stairway_lights
        default:
          - service: light.turn_on
            data:
              entity_id: light.stairway_lights
              brightness: 80
          - delay:
              seconds: 20
          - service: light.turn_off
            entity_id: light.stairway_lights

  ###############################################################################
  #   Basement Stairs
  ###############################################################################

  - id: "K9VHA5geKa48ZhL9Yhd668H5O2M0uebxv0D2douA3Q8uC43GcVVPY122r35m0W14"
    alias: Light - Turn basement stairs light on
    trigger:
      platform: state
      entity_id: binary_sensor.bs_hw_bm_door_contact
      to: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.bs_bm_stairs

  - id: "42Q1AG67A09k613Vx57egV8nPs91kAjyOr0kL034FRSP3NqSI2iTFyHsIb17dN43"
    alias: Light - Turn basement stairs light off
    trigger:
      platform: state
      entity_id: binary_sensor.bs_hw_bm_door_contact
      to: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.bs_bm_stairs

  ###############################################################################
  #   Entrance light
  ###############################################################################

  - id: "1blq746VvRQTAyquqG8UVXpRSIt2pwfgLtLqOX9z1YmCXfBC8Dn4qkgfSNSzSuTH"
    alias: Light - Manage entrance light with motion
    trigger:
      platform: state
      entity_id: binary_sensor.se_out_entrance_occupancy
      to: "on"
    condition:
      condition: numeric_state
      entity_id: sensor.se_out_entrance_illuminance_lux
      below: 400
    action:
      - service: light.turn_on
        entity_id: ight.eingangstur
      - delay: 
          minutes: 1
      - serivce: light.turn_off
        entity_id: ight.eingangstur

###############################################################################
#   Light Scenes
###############################################################################

scene:
  - name: Movietime
    icon: mdi:movie
    entities:
      light.li_lr_lightstrip:
        state: "off"
      light.li_lr_ceiling:
        state: "off"
      light.li_lr_deco:
        state: "on"
        brightness: 80
        rgb_color: [0, 255, 0]

  - name: Abendbeleuchtung
    icon: mdi:television-ambient-light
    entities:
      light.li_lr_lightstrip:
        state: "on"
        brightness: 200
        rgb_color: [255, 214, 170]
      light.li_lr_ceiling:
        state: "off"
      light.li_lr_deco:
        state: "on"
        brightness: 200
        rgb_color: [255, 214, 170]
      light.li_of_cb_bloom:
        state: "on"
        brightness: 200
        rgb_color: [255, 214, 170]
      switch.pg_hw_deco:
        state: "on"


  - name: Youtube
    icon: mdi:youtube
    entities:
      light.li_of_cb_bloom:
        state: "on"
        brightness: 255
        rgb_color: [0, 126, 126]
      light.keylight:
        state: "on"
      light.rgbicww_floor_lamp:
        state: "on"
        brightness: 255
        rgb_color: [222, 159, 0]

# Input Booleans
input_boolean:
  evening_lightning_default:
    name: Abendbeleuchtung
    initial: off
    icon: mdi:weather-sunset

  away_from_heating:
    name: Keine Heizung
    initial: off

  media:
    name: Media
    initial: off
    icon: mdi:movie

  nightmode:
    name: Nachtmodus
    initial: off
    icon: mdi:weather-night
