---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   05.06.2022
#   @package        :   Roller Shutter
#   @description    :   Roller Shutter automations
###############################################################################

automation:
  # General - Sunset and Sunrise
  - id: "XGNJ72jbiDJofWQrhaN8XCHDDMyjR3JvMJ74HzXeWdYFgBDDxh42FzCLWBXJpg8X"
    alias: Roller Shutter - Open RS on sunrise
    trigger:
      platform: sun
      event: sunrise
    action:
      - service: cover.open_cover
        entity_id:
          - cover.jalousie_kueche_position
          - cover.cover_cb_office_position_1
          - cover.cover_pt_office_position_1
          - cover.cover_diningroom_position_1
          - cover.cover_guestroom_position_1
          - cover.cover_livingroom_position_1

  - id: "icyVhTiwIRoq9RHu2lMlHrqyWYIsnw3npKG5XEBSPEFJDfElF0VXf438wUQkpfl3"
    alias: Close east roller shutter on sunrise
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      attribute: azimuth
      above: 50
    action:
      - service: cover.set_cover_position
        target:
          entity_id:
            - cover.cover_cb_office_position_1
            - cover.cover_pt_office_position_1
            - cover.cover_diningroom_position_1
            - cover.cover_guestroom_position_1
        data:
          position: 30

  - id: "MBp5q6goumZHMXfA9Jf2FyMwC2COAGwk1Ot4PGeW1uhYuX6YdQ8FMCv28yP06PFr"
    alias: Open east roller shutter
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      attribute: azimuth
      above: 120
    action:
      service: cover.open_cover
      target:
        entity_id:
          - cover.rolladen_osten

  - id: "Lz7KK3UsZYX86eYtIqALJg0ymEkb8kiFVUtop5VREPfvSRA8hothi6Pm7DLC2nXJ"
    alias: Close south roller shutter on sunrise
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      attribute: azimuth
      above: 125
    condition:
      - condition: state
        entity_id: sensor.weather_day
        state: summerday
    action:
      service: cover.set_cover_position
      target:
        entity_id:
          - cover.cover_diningroom_position_1
      data:
        position: 30

  - id: "1N1iSsMdfyVb9muoSJ6WtpmDeyQT3KNQN6PK5nigweaCifrvrHwA8sFRwRDForF6"
    alias: Open south roller shutter on sunrise
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      attribute: azimuth
      above: 180
    action:
      service: cover.open_cover
      target:
        entity_id:
          - cover.cover_diningroom_position_1

  - id: "Voj8X3oVhyucQvmmPusxTTTMAkt2tdBg7eMGNth93kodUFYtRYKgFh6pYMEqR8Kj"
    alias: Roller Shutter - Close RS on sunset
    trigger:
      platform: sun
      event: sunset
    condition:
      - condition: state
        entity_id: sensor.weather_day
        state: normalday
    action:
      - service: cover.close_cover
        entity_id:
          - cover.jalousie_kueche_position
          - cover.cover_cb_office_position_1
          - cover.cover_diningroom_position_1
          - cover.cover_guestroom_position_1
      - service: cover.set_cover_position
        target:
          entity_id:
            - cover.cover_pt_office_position_1
            - cover.cover_bedroom_position_1
        data:
          position: 45
      - service: cover.set_cover_position
        target:
          entity_id:
            - cover.cover_livingroom_position_1
        data:
          position: 55

  # Kitchen - Window Condition
  - id: "xzQaaQNMiCi8fPmrzXQZkq7TJfFKop9GwZjTsMnpu9NduzZgRFEzbgH8Ld8b3Eys"
    alias: Roller Shutter - Open RS if kitchen window opens
    trigger:
      platform: state
      entity_id: binary_sensor.bs_ki_window_contact
      to: "on"
    condition:
      - condition: state
        entity_id: cover.jalousie_kueche_position
        state: "closed"
    action:
      - service: cover.open_cover
        entity_id: cover.jalousie_kueche_position

  - id: "Nwqe8MEYabWmXujBRKJf6hoyWMMhYyCaYBqdXQJxYg8bx43VKrhpfcVsdgZN4hkU"
    alias: Roller Shutter - Close RS if kitchen window is closed
    trigger:
      platform: state
      entity_id: binary_sensor.bs_ki_window_contact
      to: "off"
    condition:
      - condition: sun
        after: sunset
    action:
      - service: cover.close_cover
        entity_id: cover.jalousie_kueche_position
