---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   06.06.2022
#   @package        :   Sensors
#   @description    :   Combine Integrations to one file
###############################################################################

sensor:
# Device Tracker
  - platform: template
    sensors:
      teqqphone:
        friendly_name: "Christian"
        value_template: >-
          {% if is_state('device_tracker.teqqphone', 'home') %}
            Daheim
          {% elif is_state('device_tracker.teqqphone', 'TIM') %}
            TIM AG
          {% else %}
            Unterwegs
          {% endif %}
        icon_template: >-
          {% if is_state('device_tracker.teqqphone','home') %}
            mdi:home-heart
          {% elif is_state('device_tracker.teqqphone', 'TIM') %}
            mdi:office-building-marker
          {% else %}
            mdi:home-export-outline
          {% endif %}

  - platform: template
    sensors:
      clios_iphone:
        friendly_name: "Petra"
        value_template: >-
          {% if is_state('device_tracker.clios_iphone', 'home') %}
            Daheim
          {% elif is_state('device_tracker.clios_iphone', 'Museum am Strom') %}
            Museum
          {% else %}
            Unterwegs
          {% endif %}
        icon_template: >-
          {% if is_state('device_tracker.clios_iphone','home') %}
            mdi:home-heart
          {% elif is_state('device_tracker.clios_iphone', 'Museum am Strom') %}
            mdi:bank
          {% else %}
            mdi:home-export-outline
          {% endif %}

# Combind temperature sensors
  - platform: min_max
    entity_ids:
      - sensor.bs_li_terrasse_device_temperature
      - sensor.se_dr_temp_temperature
      - sensor.se_lr_temp_temperature
    type: median
    name: temperature_livingroom

  - platform: min_max
    entity_ids:
      - sensor.se_of_pt_temp_temperature
      - sensor.se_of_cb_temp_temperature
      - sensor.bs_of_cb_window_device_temperature
      - sensor.bs_of_pt_window_device_temperature
    type: median
    name: temperature_office

  - platform: min_max
    entity_ids:
      - sensor.kuche_sensor_temperature
      - sensor.bs_ki_window_temperature
    type: median
    name: temperature_kitchen

  - platform: min_max
    entity_ids:
      - sensor.bs_hw_bm_door_temperature
      - sensor.hue_motion_sensor_1_temperature_2
      - sensor.hue_motion_sensor_1_temperature
    type: median
    name: temperature_hallway

  - platform: min_max
    entity_ids:
      - sensor.se_br_temp_temperature
      - sensor.bs_br_window_temperature
    type: median
    name: temperature_bathroom

  - platform: min_max
    entity_ids:
      - sensor.se_mbr_temp_temperature
    type: median
    name: temperature_bedroom

  - platform: min_max
    entity_ids:
      - sensor.temperature_wohnzimmer
      - sensor.temperature_arbeitszimmer
      - sensor.temperature_kitchen
      - sensor.temperature_bathroom
      - sensor.temperature_hallway
      - sensor.temperature_bedroom
    type: median
    name: temperature_house

# Combind humidity sensors
  - platform: min_max
    entity_ids:
      - sensor.se_dr_temp_humidity
      - sensor.se_lr_temp_humidity
    type: median
    name: humidity_livingroom

  - platform: min_max
    entity_ids:
      - sensor.se_of_pt_temp_humidity
      - sensor.se_of_cb_temp_humidity
    type: median
    name: humidity_office

  - platform: min_max
    entity_ids:
      - sensor.se_hw_temp_humidity
    type: median
    name: humidity_hallway

  - platform: min_max
    entity_ids:
      - sensor.se_mbr_temp_humidity
    type: median
    name: humidity_bedroom

  - platform: min_max
    entity_ids:
      - sensor.se_br_temp_humidity
    type: median
    name: humidity_bathroom

  - platform: min_max
    entity_ids:
      - sensor.wz_hum_mean
      - sensor.az_hum_mean
      - sensor.humidity_hallway
      - sensor.humidity_bedroom
      - sensor.humidity_bathroom
    type: median
    name: humidity_house