---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   23.04.2022
#   @package        :   Sun
#   @description    :   Sun integration and Manipulations
###############################################################################

# Integration
sun:
  elevation: !env_var HASS_ELEVATION

# Sensors
sensor:
  - platform: template
    sensors:
      nextsunrise:
        friendly_name: 'Next Sunrise'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %H:%M') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-up
      nextsunset:
        friendly_name: 'Next Sunset'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %H:%M') | replace(" 0", "") }}
        icon_template: mdi:weather-sunset-down