---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   29.07.2023
#   @package        :   Tesla
#   @description    :   Tesla Solar Charging
###############################################################################

###############################################################################
#   Input Select
###############################################################################

input_select:
  tesla_charing_mode:
    name: Tesla charging mode
    options:
      - none
      - solar
      - tibber
      - adhoc

###############################################################################
#   Sensors
###############################################################################

sensor:
  - platform: template
    sensors:
      tesla_max_charge:
        unit_of_measurement: A
        value_template: >-
          {{ (states('sensor.pv_prod_ges') | float(0) - states('sensor.pv_wr_pc_pv_to_battery_power') | float(0) - 650) * 0.0014 }}

  - platform: template
    sensors:
      tesla_charge_kw:
        unit_of_measurement: kWh
        value_template: >-
          {{ (states('number.teqqcar_charge_limit') | float(0) * 240 / 1000 * 3) | round(1)}}

  - platform: template
    sensors:
      teqqcar_charging_time:
        friendly_name: "Dauer bis voll"
        value_template: >
          {{ (states.sensor.teqqcar_charging_rate.attributes.time_left) }}
        icon_template: mdi:timer-sync-outline

###############################################################################
#   MQTT Sensors
###############################################################################

mqtt:
  sensor:
    - name: tesla_charge_energy_added
      state_topic: "teslamate/cars/1/charge_energy_added"
      device_class: energy
      unit_of_measurement: kWh
      icon: mdi:battery-charging

    - name: tesla_charger_power
      state_topic: "teslamate/cars/1/charger_power"
      device_class: power
      unit_of_measurement: kW
      icon: mdi:lightning-bolt

    - state_topic: "house/tesla/charging"
      name: "Tesla charging"

###############################################################################
#   Automations
###############################################################################

automation:
###############################################################################
#   Set Charing Modes
###############################################################################

  - id: "DsaBb10TlDRx1sJC3WswzOEdzmD11TAeHG9k4UKuX8KdZ7iqDJTql5bunG4kB2Vb"
    alias: Tesla - Set Charging Mode to Tibber
    trigger:
      - platform: state
        entity_id: sensor.electricity_price_helmerichstr_3
        attribute: price_level
        to: 
          - CHEAP
          - VERY_CHEAP
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.teqqcar_location_tracker
            state: home
          - condition: state
            entity_id: binary_sensor.teqqcar_charging
            state: "off"
          - condition: state
            entity_id: switch.teqqcar_charger
            state: "off"
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.tesla_charing_mode
        data:
          option: tibber

  - id: "eLR94m3Z0DpMlFrSTs3PFrVnnd2DAtoiSw9oi4DJmsEyZbgCxKA6E8ASx7NFngXT"
    alias: Tesla - Set Charging Mode to Solar
    trigger:
      - platform: time_pattern
        minutes: "/2"
        seconds: 00
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.teqqcar_location_tracker
            state: home
          - condition: state
            entity_id: binary_sensor.teqqcar_charging
            state: "off"
          - condition: state
            entity_id: switch.teqqcar_charger
            state: "off"
          - condition: numeric_state
            entity_id: sensor.pv_wr_pc_battery_soc
            above: 95
          - condition: numeric_state
            entity_id: sensor.pv_prod_ges
            above: 1500
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.tesla_charing_mode
            state: tibber
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.tesla_charing_mode
        data:
          option: solar

  - id: "syy3rAlQjcW5LCspRYUScFjT0c8cpPZmkAVE0pYwtcb1LpGm6T4mf6rrfmGZfgrZ"
    alias: Tesla - Set Charging Mode from Tibber to None
    trigger:
      - platform: state
        entity_id: sensor.electricity_price_helmerichstr_3
        attribute: price_level
        to: NORMAL
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.teqqcar_location_tracker
            state: home
          - condition: state
            entity_id: binary_sensor.teqqcar_charging
            state: "off"
          - condition: state
            entity_id: switch.teqqcar_charger
            state: "off"
          - condition: state
            entity_id: input_select.tesla_charing_mode
            state: tibber
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.tesla_charing_mode
        data:
          option: none

  - id: "TqB9rhNN0ks8cgeNbOc6h82aLiZvOx00InxCAPJaPXZtqKrvaNhDhnlCZMjT6ppi"
    alias: Tesla - Set Charging Mode from Solar to None
    trigger:
      - platform: time_pattern
        minutes: "/10"
        seconds: 00
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.teqqcar_location_tracker
            state: home
          - condition: state
            entity_id: input_select.tesla_charing_mode
            state: solar
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.pv_prod_ges
            below: 1500
          - condition: numeric_state
            entity_id: sensor.pv_wr_pc_battery_soc
            below: 90
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.tesla_charing_mode
        data:
          option: none

  - id: "rKjCLpnT5IiWW0V0NvSh53erRKGG7Q3fhxpyeNpdFOBSQVeumixk4SQhiWMG76sU"
    alias: Tesla - Stop Charging
    trigger:
      - platform: state
        entity_id: input_select.tesla_charing_mode
        to: none
    action:
      - service: switch.turn_off
        entity_id: switch.teqqcar_charger

###############################################################################
#   Solar charging
###############################################################################

  - id: "bwGTmaBKDkGYAnyR3NfF713cunyaPCGjlh1sknCL2FMCJYzew8FZciEm3ihPIDHb"
    alias: "Tesla - Solar - Start charging"
    trigger:
      - platform: state
        entity_id: input_select.tesla_charing_mode
        to: solar
    action:
      - service: switch.turn_on
        entity_id: switch.teqqcar_charger
      - service: number.set_value
        entity_id: number.teqqcar_charge_limit
        data:
          value: 90
      - service: number.set_value
        entity_id: number.teqqcar_charging_amps
        data:
          value: 5

  - id: "1Mn87deVpQqotoCcoP2ZmmuqSYGtobPGMx8bLqNJLCDdMPLUVOydAa0CxnLO6ZwJ"
    alias: Tesla - Solar - Adjust charging speed
    trigger:
      - platform: time_pattern
        minutes: "/1"
        seconds: 00
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: switch.teqqcar_charger
            state: "on"
          - condition: state
            entity_id: device_tracker.teqqcar_location_tracker
            state: home
          - condition: state
            entity_id: input_select.tesla_charing_mode
            state: solar
    action:
      service: script.adjust_tesla_charging

###############################################################################
#   Tibber charging
###############################################################################

  - id: "n4QsEj7u0wMOujlmHFuBacDcaYZpHbzbSmnEYr4JvjOSrXxe6YWCJnUTPUq45TXv"
    alias: "Tesla - Tibber - Start charging"
    trigger:
      - platform: state
        entity_id: input_select.tesla_charing_mode
        to: tibber
    action:
      - service: switch.turn_on
        entity_id: switch.teqqcar_charger
      - service: number.set_value
        entity_id: number.teqqcar_charge_limit
        data:
          value: 80
      - service: number.set_value
        entity_id: number.pv_wr_pc_battery_min_soc
        data:
          value: 100
      - service: number.set_value
        entity_id: number.teqqcar_charging_amps
        data:
          value: 16
      - service: notify.telegram_group
        data:
          message: >
            Tesla wird über Netzstrom geladen.

            Derzeitiger kWh Preis {{ states("sensor.electricity_price_helmerichstr_3") }}

###############################################################################
#   AdHoc charging
###############################################################################

  - id: "u4OGbshWZ9Ddk4Rq0h2HfZ6OcjSRQn4jWi9W4gKphA5PoME5PwzZbB6aKQTBzNki"
    alias: "Tesla - AdHoc - Start charging"
    trigger:
      - platform: state
        entity_id: input_select.tesla_charing_mode
        to: adhoc
    action:
      - service: switch.turn_on
        entity_id: switch.teqqcar_charger
      - service: number.set_value
        entity_id: number.teqqcar_charge_limit
        data:
          value: 80
      - service: number.set_value
        entity_id: number.pv_wr_pc_battery_min_soc
        data:
          value: 100
      - service: number.set_value
        entity_id: number.teqqcar_charging_amps
        data:
          value: 16

###############################################################################
#   Scripts
###############################################################################

script:
  "adjust_tesla_charging":
    alias: Charge tesla
    sequence:
      - service: number.set_value
        data:
          value: >-
            {{ (states('sensor.tesla_max_charge') | float(0) | round(0)) }}
        target:
          entity_id: number.teqqcar_charging_amps
    mode: single
