---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   13.02.2022
#   @package        :   Tesla
#   @description    :   Tesla Solar Charging
###############################################################################

sensor:
  - platform: template
    sensors:
      tesla_max_charge:
        unit_of_measurement: A
        value_template: >-
          {{ (states('sensor.pv_prod_ges') | float(0) - states('sensor.pv_wr_pc_pv_to_battery_power') | float(0) - 650) * 0.0014 }}

  - platform: template
    sensors:
      tesla_charge_kw:
        unit_of_measurement: kWh
        value_template: >-
          {{ (states('number.teqqcar_charge_limit') | float(0) * 240 / 1000 * 3) | round(1)}}

  - platform: template
    sensors:
      teqqcar_charging_time:
        friendly_name: 'Dauer bis voll'
        value_template: >
          {{ (states.sensor.teqqcar_charging_rate.attributes.time_left) }}
        icon_template: mdi:timer-sync-outline

mqtt:
  sensor:
    - name: tesla_charge_energy_added
      state_topic: "teslamate/cars/1/charge_energy_added"
      device_class: energy
      unit_of_measurement: kWh
      icon: mdi:battery-charging

automation:
  - id: TAXsk8rAemJQ45aVaIuCfU7qwE70hSAen6xA9wNbstXnw00nytstkDORma02mrzi
    alias: Tesla - Start charging if pv production over 1500
    trigger:
    - platform: time_pattern
      minutes: '/10'
      seconds: 00
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.teqqcar_location_tracker
            state: home
          - condition: state
            entity_id: binary_sensor.teqqcar_charging
            state: 'off'
          - condition: state
            entity_id: switch.teqqcar_charger
            state: 'off'
          - condition: numeric_state
            entity_id: sensor.pv_wr_pc_battery_soc
            above: '90'
          - condition: numeric_state
            entity_id: sensor.pv_prod_ges
            above: '1500'
    action:
    - service: switch.turn_on
      target:
        entity_id: switch.teqqcar_charger
    mode: single


  - alias: Adjust charging speed
    trigger:
    - platform: time_pattern
      minutes: '/1'
      seconds: 00
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: switch.teqqcar_charger
            state: 'on'
          - condition: state
            entity_id: device_tracker.teqqcar_location_tracker
            state: home
    action:
      service: script.adjust_tesla_charging

  - id: rWAmk5RZbNron9gsZN3GcOXnsr0EppOny5aJQJB0UNgGDN7lSSUvtqqBwLgdGCKP
    alias: Tesla - Stop charging if solar generation is below 1 kW
    description: ''
    trigger:
    - platform: numeric_state
      entity_id: sensor.pv_prod_ges
      below: '1000'
      for: 00:01:00
    condition:
      - condition: state
        entity_id: device_tracker.teqqcar_location_tracker
        state: home
    action:
    - service: switch.turn_off
      target:
        entity_id: switch.teqqcar_charger
    mode: single

  - id: p86ivzlxVwSfyWxjnHEPkvKpTuqbw9yPdF7x7aaGFGUhm1uVdG8rjaDa8SpmMEcp
    alias: Tesla - Stop charging if solar battery is under 90 %
    description: ''
    trigger:
    - platform: numeric_state
      entity_id: sensor.pv_wr_pc_battery_soc
      below: '90'
    condition:
      - condition: state
        entity_id: device_tracker.teqqcar_location_tracker
        state: home
    action:
    - service: switch.turn_off
      target:
        entity_id: switch.teqqcar_charger
    mode: single

script:
  'adjust_tesla_charging':
    alias: Charge tesla
    sequence:
    - service: number.set_value
      data:
        value: >-
          {{ (states('sensor.tesla_max_charge') | float(0) | round(0)) }}
      target:
        entity_id: number.teqqcar_charging_amps
    mode: single
