---
###############################################################################
#   @author         :   Christian Birkenbeul
#   @date           :   08.09.2023
#   @package        :   Windows
#   @description    :   Window alerts
###############################################################################

###############################################################################
# Bathroom
###############################################################################
automation:
  - id: "yhe3ux5QGuhJ5Po4s5wdAdS7BsZwJw8PFjwwtqRstsPcwFH6WF2uevG8MPKz2kya"
    alias: Notification if bathroom window is open
    description: ''
    trigger:
      - platform: state
        entity_id: binary_sensor.bs_br_window_contact
        to: 'on'
        for:
          hours: 0
          minutes: 10
          seconds: 0
    condition:
      - condition: state
        entity_id: sensor.weather_day
        state: normalday
    action:
      - repeat:
          while:
            - condition: state
              entity_id: sensor.weather_day
              state: normalday
            - condition: state
              entity_id: binary_sensor.bs_br_window_contact
              state: 'on'
          sequence:
            - service: notify.telegram_group
              data:
                message: Das Fenster im Bad ist offen.
            - delay:
                minutes: 10
    mode: single
