---
- alias: Set House to away mode
  trigger:
    - platform: state
      entity_id:
        - group.devices
      to: "not_home"
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.home_mode
        option: away
