---
- alias: Set House to sleep mode
  trigger:
    - platform: time
      at: '01:00:00'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.home_mode
        option: sleep
